FROM node:22-alpine AS builder

WORKDIR /app

RUN npm install -g expo-cli

COPY .env.prod .env

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npx expo export -p web --clear

FROM nginx:1.25-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80