#!/bin/bash

# --- CONFIGURACIÓN ---
# Directorio donde está tu proyecto en el servidor
# Si se ejecuta desde el mismo directorio, podemos usar $(pwd)
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colores para logs bonitos
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${YELLOW}🚀 Iniciando despliegue de Iter Monorepo...${NC}"

# 1. Ir al directorio
cd "$PROJECT_DIR" || { echo -e "${RED}❌ Error: No encuentro el directorio $PROJECT_DIR${NC}"; exit 1; }

# 2. Bajar últimos cambios de Git (Opcional si se usa --no-reset)
if [[ "$1" == "--no-reset" ]]; then
  echo -e "${YELLOW}⏩ Saltando descarga de cambios (usando archivos locales)...${NC}"
else
  echo -e "${YELLOW}📥 Descargando cambios desde GitHub (main)...${NC}"
  git fetch origin main
  git reset --hard origin/main
fi

# 3. Permisos (por si acaso han cambiado scripts)
chmod +x deploy.sh

# 4. Asegurar archivos .env (Necesarios para Docker Compose)
echo -e "${YELLOW}🔑 Verificando archivos de entorno (.env)...${NC}"

if [ ! -f ".env" ]; then
  echo -e "${YELLOW}⚠️ .env root no encontrado. Creando uno básico...${NC}"
  echo "# Autogenerated by deploy.sh" > .env
  echo "POSTGRES_USER=postgres" >> .env
  echo "POSTGRES_PASSWORD=root" >> .env
  echo "POSTGRES_DB=iter_db" >> .env
  # Apuntamos a host.docker.internal para acceder a la BD del host
  echo "DATABASE_URL=postgresql://postgres:root@host.docker.internal:5432/iter_db?schema=public" >> .env
fi

if [ ! -f "apps/api/.env" ]; then
  echo -e "${YELLOW}⚠️ apps/api/.env no encontrado. Creando uno básico...${NC}"
  echo "# Autogenerated by deploy.sh" > apps/api/.env
  echo "PORT=3000" >> apps/api/.env
fi

if [ ! -f "apps/web/.env" ]; then
  echo -e "${YELLOW}⚠️ apps/web/.env no encontrado. Creando uno básico...${NC}"
  echo "# Autogenerated by deploy.sh" > apps/web/.env
  echo "NEXT_PUBLIC_API_URL=https://api-iter.kore29.com" >> apps/web/.env
fi

# 5. Reconstrucción inteligente (Docker Prod)
echo -e "${YELLOW}🐳 Construyendo imágenes de Producción (Multi-stage)...${NC}"
# Usamos --build para forzar que coja los cambios de código
docker compose -f docker-compose.prod.yml up --build -d --remove-orphans

# 5. Verificación de salud
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✅ ¡Despliegue completado con éxito!${NC}"
  echo -e "${GREEN}👉 Web: https://iter.kore29.com${NC}"
  echo -e "${GREEN}👉 API: https://api-iter.kore29.com${NC}"
  
  # 6. Limpieza de basura espacial (Importante en VPS)
  echo -e "${YELLOW}🧹 Limpiando imágenes antiguas para ahorrar espacio...${NC}"
  docker image prune -f
else
  echo -e "${RED}❌ Ocurrió un error al levantar los contenedores.${NC}"
  exit 1
fi