name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar script de despliegue
        run: |
          chmod +x deploy.sh
          ./deploy.sh
